In [1]:
import numpy as np
from scipy import linalg

In [2]:
A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
w, v = linalg.eig(A)

In [3]:
print(w)

[ 4.31662479e+00+0.j -2.31662479e+00+0.j  1.93041509e-17+0.j]


In [4]:
print(v)

[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


In [5]:
print(v.T)

[[ 0.58428153  0.80407569  0.10989708]
 [ 0.73595785 -0.38198836 -0.55897311]
 [ 0.40824829 -0.81649658  0.40824829]]


In [6]:
lam = w[1]
u = v.T[1]

In [7]:
print(np.dot(A,u))

[-1.7049382   0.88492371  1.29493096]


In [8]:
print(lam*u)

[-1.7049382 +0.j  0.88492371-0.j  1.29493096-0.j]
